/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logapi;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        nrLogClient classUnderTest = new nrLogClient();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
